feat(context): support breaking change in structlog 24.1.0
event_dict.update(structlog.get_logger()._context._dict)
AttributeError: 'dict' object has no attribute '_dict'